### ISSUE TITLE
Ошибка 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by ghost** [sdnv0x4d/transfer-yt-subs#5]
Там ничего нет, только сообщение о том, что "Доступ Заблокирован". Там даже кнопки никакой нет. Как решить эту проблему?

**Comment by sdnv0x4d** [comment]
Привет!
Важно, чтобы в настройках google api в поле redirect_uri был указан линк вместе со слешем на конце.
Также, не сразу подтягиваются изменения в приложении, порой нужно ждать до нескольких часов

**Comment by sdnv0x4d** [comment]
Если у тебя решился вопрос - напиши что именно сделал и закрой issue
Мб другим пригодится

**Comment by ghost** [comment]
> Если у тебя решился вопрос - напиши что именно сделал и закрой issue
> Мб другим пригодится

я пытаюсь попробовать заново. Я кажется в конце слэши забыл добавить

**Comment by ghost** [comment]
> Привет!
> Важно, чтобы в настройках google api в поле redirect_uri был указан линк вместе со слешем на конце.
> Также, не сразу подтягиваются изменения в приложении, порой нужно ждать до нескольких часов

спасибо, помогло. Я забыл слэши в конце добавить.
